import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const project = await prisma.project.findFirst();
  if (!project) {
    console.error('No project found');
    return;
  }

  console.log("Adding BSS Crisis Scenarios...\n");

  const crises = [
    // ========== Q1: VEGAS / D.C. / ASIA ==========
    {
      name: 'Casino AI Math Meltdown',
      codeName: 'JACKPOT',
      location: 'Las Vegas, NV',
      crisisType: 'Technical / Financial',
      clientType: 'Fortune 500 Casino Chain',
      severity: 'critical',
      timeframe: 'Q1',
      description: 'AI-driven betting system glitches during high-stakes poker tournament, risking exposure of insider algorithms and regulatory violations.',
      situation: 'Casino AI miscalculates odds mid-high roller tournament. Gaming commission breathing down their necks.',
      complications: 'Political pressure from gaming commission. Investors threaten to pull. Media circling.',
      resolution: 'BSS patches the math system in real time while spinning narrative for investors.',
      bssTeam: JSON.stringify(['Addie', 'Nate Archer', 'Caroline']),
      stakes: 'Casino chain valuation, gaming licenses, investor confidence',
    },
    {
      name: "Senator's Offshore Nightmare",
      codeName: 'SHADOW LEDGER',
      location: 'Washington, D.C.',
      crisisType: 'Political / Financial',
      clientType: 'Government Official',
      severity: 'critical',
      timeframe: 'Q1',
      description: "A powerful senator's shell companies leak, threatening to tank markets and a defense contract.",
      situation: 'Offshore ties about to leak, tanking markets and defense contracts.',
      complications: 'Multiple paper trails, foreign bank records, rival politicians circling.',
      resolution: 'BSS scrubs financials, buries the paper trail, cuts backroom deal with regulators.',
      bssTeam: JSON.stringify(['Addie', 'Marcus Vega', 'Jasper']),
      stakes: 'Defense contracts, market stability, political career',
    },
    {
      name: 'Collapsing Bridge Infrastructure',
      codeName: 'MONSOON',
      location: 'Manila, Philippines',
      crisisType: 'Infrastructure / Humanitarian',
      clientType: 'European Construction Firm',
      severity: 'critical',
      timeframe: 'Q1',
      description: 'Massive infrastructure project at risk of collapse during monsoon season, threatening villages and ruining European construction giant.',
      situation: 'Monsoon threatens massive infrastructure failure. Villages at risk.',
      complications: 'Weather window closing, local politics, construction defects.',
      resolution: 'Structural shoring + evacuation. Spin as "humanitarian response." Force government to hand project to BSS-backed firm.',
      bssTeam: JSON.stringify(['Gideon', 'Colt', 'Engineering team']),
      stakes: 'Lives, $2B contracts, firm reputation',
    },
    {
      name: 'Fortune 100 CEO Sex Tape',
      codeName: 'INDISCRETION',
      location: 'Los Angeles, CA',
      crisisType: 'Scandal / Reputation',
      clientType: 'Fortune 100',
      severity: 'high',
      timeframe: 'Q1',
      description: 'Fortune 100 CEO caught in private scandal. BSS must contain, bury, and reposition.',
      situation: 'Private footage threatens to surface before earnings call.',
      complications: 'Multiple copies, blackmailers, shaken wife needs handling.',
      resolution: 'BSS hacks, buys, and buries footage. Repositions CEO as "family-first" executive. Wives club runs interference with wife.',
      bssTeam: JSON.stringify(['Addie', 'Caleb Strickland', 'Elena']),
      stakes: 'Stock price, board confidence, family',
    },

    // ========== Q2: EUROPE / AFRICA / MIDDLE EAST ==========
    {
      name: 'Royal Family Divorce Crisis',
      codeName: 'CROWN DIVIDE',
      location: 'Middle East',
      crisisType: 'Political / Financial',
      clientType: 'Royal Family',
      severity: 'critical',
      timeframe: 'Q2',
      description: 'Middle Eastern royal family divorce threatens to destabilize a $2B defense deal.',
      situation: 'Divorce proceedings could expose defense contracts and political alliances.',
      complications: 'Western media attention, competing royal factions, arms dealers.',
      resolution: 'BSS negotiates terms quietly, spins Western press, ensures arms contracts stay intact.',
      bssTeam: JSON.stringify(['Jasper', 'Selene', 'Marcus']),
      stakes: '$2B defense deal, regional stability',
    },
    {
      name: 'Olympic Bribery Exposé',
      codeName: 'GOLD MEDAL',
      location: 'International',
      crisisType: 'Scandal / Political',
      clientType: 'Olympic Bid Committee',
      severity: 'high',
      timeframe: 'Q2',
      description: 'International Olympic bid accused of corruption. BSS must contain the fallout.',
      situation: 'Bribery allegations surface before IOC vote.',
      complications: 'Multiple whistleblowers, international media, competing bid cities.',
      resolution: 'BSS plants counter-leaks, reframes narrative as "strategic partnerships," covers tracks.',
      bssTeam: JSON.stringify(['Addie', 'Derek Callahan', 'Media team']),
      stakes: 'Olympic bid, city reputation, $billions in development',
    },
    {
      name: 'Pharma Trial Cover-Up',
      codeName: 'SIDE EFFECT',
      location: 'Geneva / Research Triangle',
      crisisType: 'Corporate / Medical',
      clientType: 'Biotech Firm',
      severity: 'critical',
      timeframe: 'Q2',
      description: "A biotech's trial data is about to reveal serious flaws. BSS must contain before FDA review.",
      situation: 'Trial data shows dangerous side effects. Whistleblower preparing to leak.',
      complications: 'FDA timeline, patient advocacy groups, short sellers.',
      resolution: 'BSS suppresses leak, reframes "failure" as "pivot to new treatments," protects valuation.',
      bssTeam: JSON.stringify(['Addie', 'Dr. Evelyn Cross', 'Legal team']),
      stakes: 'Drug approval, stock price, patient safety narrative',
    },
    {
      name: 'Oil Spill PR War',
      codeName: 'BLACK TIDE',
      location: 'Lagos, Nigeria',
      crisisType: 'Environmental / Corporate',
      clientType: 'Energy Firm',
      severity: 'critical',
      timeframe: 'Q2',
      description: 'Major oil spill threatens $10B energy firm. BSS must contain environmentally and in media.',
      situation: 'Spill spreading. Environmental activists descending. Stock crashing.',
      complications: 'Nigerian government pressure, international NGOs, competing firms smelling blood.',
      resolution: 'Contain spill with tech team. Spin as "rapid environmental response." Broker merger with green energy firm.',
      bssTeam: JSON.stringify(['Colt', 'Gideon', 'Darius Cole']),
      stakes: '$10B valuation, environmental liability, CEO position',
    },
    {
      name: 'Oligarch Yacht Scandal',
      codeName: 'ANCHOR',
      location: 'Monaco',
      crisisType: 'Scandal / Criminal',
      clientType: 'Russian Oligarch',
      severity: 'critical',
      timeframe: 'Q2',
      description: 'Leaked tapes of parties with potentially illegal activities on oligarch yacht.',
      situation: 'Tapes circulating through European tabloids and law enforcement.',
      complications: 'Multiple jurisdictions, seized assets risk, political enemies.',
      resolution: 'Destroy evidence. Frame as "political smear campaign." Shore up London banker allies.',
      bssTeam: JSON.stringify(['Nikolai', 'Selene', 'Jasper']),
      stakes: 'Criminal prosecution, asset seizure, reputation',
    },

    // ========== Q3: US / LATIN AMERICA / ASIA ==========
    {
      name: 'Cartel Money Laundering Exposure',
      codeName: 'SAND CASTLE',
      location: 'Miami, FL',
      crisisType: 'Financial / Criminal',
      clientType: 'Crypto Startup',
      severity: 'critical',
      timeframe: 'Q3',
      description: 'Crypto startup discovered to be laundering cartel money through Miami beachfront properties.',
      situation: 'DEA closing in. Startup founders panicking. Properties frozen.',
      complications: 'Cartel threats, federal investigation, bank compliance.',
      resolution: 'Cut founders loose. Restructure ownership. Plant evidence pointing elsewhere.',
      bssTeam: JSON.stringify(['Marcus Vega', 'Caroline', 'Legal team']),
      stakes: 'Criminal charges, cartel retaliation, property portfolio',
    },
    {
      name: 'MLS Owner Blackmail',
      codeName: 'PITCH BLACK',
      location: 'Miami, FL',
      crisisType: 'Scandal / Sports',
      clientType: 'MLS Team Owner',
      severity: 'high',
      timeframe: 'Q3',
      description: 'MLS team owner blackmailed with compromising photos before expansion draft.',
      situation: 'Photos about to surface. Season opener in 3 days.',
      complications: 'Multiple blackmailers, league pressure, sponsor panic.',
      resolution: 'Derek Callahan handles sports angle. BSS tracks blackmailers. Photos buried.',
      bssTeam: JSON.stringify(['Addie', 'Derek Callahan', 'Caleb']),
      stakes: 'Team ownership, sponsorships, expansion plans',
    },
    {
      name: 'Dam Failure South America',
      codeName: 'FLOOD GATE',
      location: 'Brazil',
      crisisType: 'Infrastructure / Corporate',
      clientType: 'European Construction Giant',
      severity: 'critical',
      timeframe: 'Q3',
      description: 'Mega-project dam at risk of collapse. Villages downstream. European contractor facing ruin.',
      situation: 'Structural failure detected. 72 hours before monsoon season peak.',
      complications: 'Local corruption, engineering cover-ups, media arriving.',
      resolution: 'Reinforce structure. Blame sabotage. Broker buyout by rival firm.',
      bssTeam: JSON.stringify(['Gideon', 'Colt', 'Nate Archer']),
      stakes: 'Lives, $3B contract, corporate survival',
    },
    {
      name: 'Medical Cargo Biohazard',
      codeName: 'PATIENT ZERO',
      location: 'In Transit to Geneva',
      crisisType: 'Medical / Logistics',
      clientType: 'Pharmaceutical',
      severity: 'critical',
      timeframe: 'Q3',
      description: 'Medical cargo en route to Geneva leaks. If exposed, global panic.',
      situation: 'Containment breach detected mid-flight. WHO preparing emergency protocols.',
      complications: 'International airspace, multiple governments, media monitoring.',
      resolution: 'Contain outbreak risk. Silence WHO panic. Use cover to reframe pharma valuation.',
      bssTeam: JSON.stringify(['Dr. Evelyn Cross', 'Logistics team', 'Addie']),
      stakes: 'Global health panic, pharma valuation, criminal liability',
    },

    // ========== Q4: GLOBAL HOT SPOTS ==========
    {
      name: 'Vatican Bank Leak',
      codeName: 'HOLY LEDGER',
      location: 'Vatican City / Rome',
      crisisType: 'Financial / Religious',
      clientType: 'Vatican',
      severity: 'critical',
      timeframe: 'Q4',
      description: 'Vatican Bank financial irregularities about to leak. Could destabilize Catholic Church globally.',
      situation: 'Italian prosecutors have documents. Media preparing exposé.',
      complications: 'Italian politics, internal Church factions, international scope.',
      resolution: 'Chris Donnelly uses Catholic connections. BSS provides cover. Controlled disclosure.',
      bssTeam: JSON.stringify(['Chris Donnelly', 'Addie', 'Marcus']),
      stakes: 'Church credibility, $billions in assets, political alliances',
    },
    {
      name: 'Art Basel Cartel Assassination Attempt',
      codeName: 'GALLERY',
      location: 'Miami Beach, FL',
      crisisType: 'Security / Criminal',
      clientType: 'Art Collector / Gallery Owner',
      severity: 'critical',
      timeframe: 'Q4',
      description: 'Cartel assassination attempt at Art Basel threatens high-profile clients. Links back to Vegas fake art plot.',
      situation: 'Hit team identified. Multiple clients at risk. Event in progress.',
      complications: 'Civilian crowd, international guests, police response.',
      resolution: 'Neutralize threat. Protect clients. Cover up connection to Vegas operation.',
      bssTeam: JSON.stringify(['Hawk', 'Colt', 'Security team']),
      stakes: 'Client lives, BSS reputation, ongoing operations',
    },
    {
      name: 'Fake Art Sting Vegas',
      codeName: 'MASTERPIECE',
      location: 'Las Vegas, NV',
      crisisType: 'Criminal / Financial',
      clientType: 'Casino Chain',
      severity: 'high',
      timeframe: 'Q4',
      description: 'Luxury casino gallery selling forgeries to international clients. Diplomatic incident brewing.',
      situation: 'Interpol investigating. Buyers include diplomats and royalty.',
      complications: 'Multiple national governments, insurance fraud, art world reputation.',
      resolution: 'BSS sets up controlled sting. Technical art analysis. PR pivot to save face for casino.',
      bssTeam: JSON.stringify(['Addie', 'Serena Ward', 'Art specialists']),
      stakes: 'Casino reputation, diplomatic relations, $millions in art',
    },
    {
      name: 'Dubai Sovereign Wealth Scandal',
      codeName: 'OASIS',
      location: 'Dubai, UAE',
      crisisType: 'Financial / Political',
      clientType: 'Sovereign Wealth Fund',
      severity: 'critical',
      timeframe: 'Q4',
      description: 'Sovereign wealth fund manager embezzlement discovered. Regional stability at risk.',
      situation: 'Missing billions traced to London properties and offshore accounts.',
      complications: 'Royal family politics, UK banking relationships, media pressure.',
      resolution: 'Quiet recovery of assets. Manager disappears. New narrative planted.',
      bssTeam: JSON.stringify(['Jasper', 'Marcus', 'Selene']),
      stakes: 'Regional stability, UK-UAE relations, fund credibility',
    },
    {
      name: 'Paris Fashion Week Espionage',
      codeName: 'HAUTE',
      location: 'Paris, France',
      crisisType: 'Corporate / Espionage',
      clientType: 'Luxury Fashion House',
      severity: 'high',
      timeframe: 'Q4',
      description: 'Industrial espionage at major fashion house. Next season designs stolen.',
      situation: 'Designs leaked to competitor. Show in 48 hours.',
      complications: 'Corporate mole, competitor leverage, media frenzy.',
      resolution: 'Identify mole. Recover designs. Plant false trail to competitor.',
      bssTeam: JSON.stringify(['Serena Ward', 'Caleb', 'European team']),
      stakes: '$hundreds of millions in designs, brand reputation',
    },
    {
      name: 'NY Hedge Fund Implosion',
      codeName: 'MARGIN CALL',
      location: 'New York City',
      crisisType: 'Financial',
      clientType: 'Hedge Fund',
      severity: 'critical',
      timeframe: 'Q4',
      description: 'Insider trading leak threatens collapse of major hedge fund. Market contagion risk.',
      situation: 'SEC investigation imminent. Positions unwinding.',
      complications: 'Multiple funds connected, systemic risk, criminal exposure.',
      resolution: 'Patch leaks. Spin as "market correction." Let rivals collapse, scoop assets.',
      bssTeam: JSON.stringify(['Marcus', 'Caroline', 'Addie']),
      stakes: 'Market stability, criminal charges, $billions in assets',
    },

    // ========== RECURRING ARC CRISES ==========
    {
      name: 'Boston Brahmin Family Secrets',
      codeName: 'BLUE BLOOD',
      location: 'Boston, MA',
      crisisType: 'Family / Political',
      clientType: 'Old Money Family',
      severity: 'high',
      timeframe: 'Recurring',
      description: 'Old money Boston family secrets threatening to go national. Charity foundation fraud, inheritance fights.',
      situation: 'Q1: Foundation audit. Q2: Funding fraud discovered. Q3: Patriarch failing. Q4: Family secrets threaten national exposure.',
      complications: 'Multiple family factions, media connections, political ties.',
      resolution: 'Chris Donnelly handles through Catholic elite connections. Multi-quarter management.',
      bssTeam: JSON.stringify(['Chris Donnelly', 'Addie', 'Boston team']),
      stakes: 'Family legacy, $billions in assets, political careers',
    },
    {
      name: 'D.C. Political Hydra',
      codeName: 'HYDRA',
      location: 'Washington, D.C.',
      crisisType: 'Political',
      clientType: 'Multiple Politicians',
      severity: 'ongoing',
      timeframe: 'Recurring',
      description: 'D.C. never has just one scandal. Every time BSS cuts off one head, two more grow back.',
      situation: 'Rotating cast of senators, lobbyists, agency heads with overlapping crises.',
      complications: 'Interconnected scandals, shifting alliances, election cycles.',
      resolution: 'Continuous management. Never fully resolved.',
      bssTeam: JSON.stringify(['Addie', 'Jessica Marlowe', 'D.C. team']),
      stakes: 'Multiple political careers, policy outcomes, BSS D.C. influence',
    },

    // ========== TECHNICAL/SCORPION-STYLE CRISES ==========
    {
      name: 'Nuclear Facility Glitch',
      codeName: 'MELTDOWN',
      location: 'Eastern Europe',
      crisisType: 'Technical / Nuclear',
      clientType: 'Energy Consortium',
      severity: 'critical',
      timeframe: 'Technical Arc',
      description: 'Eastern European nuclear facility glitch tied to corruption in supply chain. Meltdown risk.',
      situation: 'Reactor readings unstable. Local officials covering up.',
      complications: 'Corruption, time pressure, international oversight.',
      resolution: 'Technical fix to stop meltdown. Spin as "successful safety test." Help energy firm profit from cover-up.',
      bssTeam: JSON.stringify(['Nate Archer', 'Technical team', 'Jasper']),
      stakes: 'Lives, environmental disaster, energy contracts',
    },
    {
      name: 'Air Traffic Control Hack',
      codeName: 'COLLISION',
      location: 'New York / Miami',
      crisisType: 'Cyber / Technical',
      clientType: 'Defense Contractor',
      severity: 'critical',
      timeframe: 'Technical Arc',
      description: 'Major U.S. hub ATC system hacked. Chaos looming. Planes at risk.',
      situation: 'System compromised. Planes in holding patterns. Media noticing.',
      complications: 'Federal involvement, time pressure, public safety.',
      resolution: 'Reboot systems on the fly. Spin as "routine glitch." Help defense contractor get cybersecurity contract.',
      bssTeam: JSON.stringify(['Caleb Strickland', 'Nate Archer', 'Cyber team']),
      stakes: 'Passenger safety, national security, defense contracts',
    },
    {
      name: 'Classified Satellite Descent',
      codeName: 'FALLING STAR',
      location: 'Global',
      crisisType: 'Aerospace / Military',
      clientType: 'Defense/Intelligence',
      severity: 'critical',
      timeframe: 'Technical Arc',
      description: 'Satellite failure could reveal classified payloads. Re-entry trajectory threatens populated area.',
      situation: 'Satellite tumbling. Classified tech at risk of recovery by adversaries.',
      complications: 'International tracking, adversary interest, public visibility.',
      resolution: 'Dr. Nate Archer recalculates trajectory. Controlled deorbit over ocean.',
      bssTeam: JSON.stringify(['Nate Archer', 'Jordan Reese', 'Jasper']),
      stakes: 'Classified tech, lives, international incident',
    },
    {
      name: 'Internet Backbone Attack',
      codeName: 'DARK WEB',
      location: 'New York City',
      crisisType: 'Cyber / Financial',
      clientType: 'Hedge Funds / Financial Sector',
      severity: 'critical',
      timeframe: 'Technical Arc',
      description: 'Attack on U.S. East Coast internet backbone threatening NYC financial district.',
      situation: 'Trading systems failing. Markets about to halt.',
      complications: 'Cascading failures, multiple institutions, federal response.',
      resolution: 'Patch vulnerability before trading halts. Leak as "minor denial-of-service." Protect client hedge funds.',
      bssTeam: JSON.stringify(['Caleb Strickland', 'Marcus', 'Cyber team']),
      stakes: 'Market stability, $trillions in trades, national security',
    },
    {
      name: 'Art Gallery Vault Lockdown',
      codeName: 'VAULT',
      location: 'Las Vegas, NV',
      crisisType: 'Security / Technical',
      clientType: 'Casino / Gallery',
      severity: 'high',
      timeframe: 'Technical Arc',
      description: 'Casino art vault locks down during heist attempt. High-value art and people trapped inside.',
      situation: 'Vault sealed. Security overridden. VIPs trapped with $100M in art.',
      complications: 'Heist in progress, hostage situation, system compromise.',
      resolution: 'Technical override. Neutralize threat. Recover art. Insurance payout.',
      bssTeam: JSON.stringify(['Hawk', 'Caleb', 'Security team']),
      stakes: '$100M art, VIP lives, casino reputation',
    },
  ];

  let created = 0;
  let updated = 0;

  for (const crisis of crises) {
    const existing = await prisma.crisis.findFirst({
      where: { name: crisis.name, projectId: project.id }
    });

    if (existing) {
      await prisma.crisis.update({
        where: { id: existing.id },
        data: crisis
      });
      console.log(`Updated: ${crisis.name}`);
      updated++;
    } else {
      await prisma.crisis.create({
        data: {
          projectId: project.id,
          ...crisis,
          status: 'planned',
        }
      });
      console.log(`Created: ${crisis.name}`);
      created++;
    }
  }

  console.log(`\nCreated: ${created}, Updated: ${updated}`);

  const count = await prisma.crisis.count();
  console.log(`Total crises: ${count}`);

  await prisma.$disconnect();
}

main().catch(console.error);
